defaults:
  - cg: fixed
  - nn: schnet
  - prior: forcefield
  - train: potential
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
  - _self_

hydra:  
  output_subdir: null  
  run:  
    dir: .  

integrator_args:
  dt: 0.001
  friction: 10.
  temperature: 300.
  length_units: "angstroms"
  energy_units: "kilocalories_per_mole"
  time_units: "picoseconds"
  temperature_units: "kelvin"


global_args:
  model_folder: "./lightning_logs/version_23473/"
  bias_force: null
  save_folder_name: "/global/cfs/cdirs/m4235/boltz_files/bba/umbrella/"
  pdb_file: "/global/cfs/cdirs/m4235/boltz_files/bba/boltz_inference/boltz_results_bba_inference/predictions/bba/bba_model_0.pdb"
  start_positions: "starting_positions_chignolin.npy"
  start_indices: "starting_index.npy"
  num_data_points: 10000
  batch_size: 10
  save_freq: 10
  chk_freq: 1000
  